// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countGeoEvents = `-- name: CountGeoEvents :one
SELECT COUNT(*) FROM "events"
`

func (q *Queries) CountGeoEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGeoEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUpcomingGeoEvents = `-- name: ListUpcomingGeoEvents :many
SELECT
    event_id,
    title,
    start_dt,
    location_name,
    source_tag,
    source_url
FROM "events"
WHERE start_dt >= NOW()
ORDER BY start_dt ASC
LIMIT $1
`

type ListUpcomingGeoEventsRow struct {
	EventID      uuid.UUID `json:"event_id"`
	Title        string    `json:"title"`
	StartDt      time.Time `json:"start_dt"`
	LocationName string    `json:"location_name"`
	SourceTag    string    `json:"source_tag"`
	SourceUrl    string    `json:"source_url"`
}

func (q *Queries) ListUpcomingGeoEvents(ctx context.Context, limit int32) ([]ListUpcomingGeoEventsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingGeoEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingGeoEventsRow
	for rows.Next() {
		var i ListUpcomingGeoEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.StartDt,
			&i.LocationName,
			&i.SourceTag,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
