// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                    uuid.UUID  `json:"id"`
	UserId                uuid.UUID  `json:"userId"`
	AccountId             string     `json:"accountId"`
	ProviderId            string     `json:"providerId"`
	AccessToken           *string    `json:"accessToken"`
	RefreshToken          *string    `json:"refreshToken"`
	AccessTokenExpiresAt  *time.Time `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt *time.Time `json:"refreshTokenExpiresAt"`
	Scope                 *string    `json:"scope"`
	IdToken               *string    `json:"idToken"`
	Password              *string    `json:"password"`
	CreatedAt             time.Time  `json:"createdAt"`
	UpdatedAt             time.Time  `json:"updatedAt"`
}

type Event struct {
	EventID      uuid.UUID   `json:"event_id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	StartDt      time.Time   `json:"start_dt"`
	EndDt        *time.Time  `json:"end_dt"`
	LocationName string      `json:"location_name"`
	Address      string      `json:"address"`
	Geom         interface{} `json:"geom"`
	SourceTag    string      `json:"source_tag"`
	SourceUrl    string      `json:"source_url"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Jwk struct {
	ID         uuid.UUID  `json:"id"`
	UserId     *uuid.UUID `json:"userId"`
	PublicKey  string     `json:"publicKey"`
	PrivateKey string     `json:"privateKey"`
	CreatedAt  time.Time  `json:"createdAt"`
	ExpiresAt  *time.Time `json:"expiresAt"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserId    uuid.UUID `json:"userId"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
	IpAddress *string   `json:"ipAddress"`
	UserAgent *string   `json:"userAgent"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type SourceHash struct {
	SourceTag   string    `json:"source_tag"`
	ContentHash string    `json:"content_hash"`
	EventID     uuid.UUID `json:"event_id"`
}

type Subscription struct {
	ID                uuid.UUID  `json:"id"`
	UserId            uuid.UUID  `json:"userId"`
	ExternalId        *string    `json:"externalId"`
	Tier              string     `json:"tier"`
	CancelAtPeriodEnd bool       `json:"cancelAtPeriodEnd"`
	Status            string     `json:"status"`
	CurrentPeriodEnd  *time.Time `json:"currentPeriodEnd"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         time.Time  `json:"updatedAt"`
}

type SystemEvent struct {
	ID        uuid.UUID `json:"id"`
	UserId    uuid.UUID `json:"userId"`
	Data      []byte    `json:"data"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type User struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"emailVerified"`
	Image         *string   `json:"image"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type Verification struct {
	ID         uuid.UUID `json:"id"`
	UserId     uuid.UUID `json:"userId"`
	Identifier string    `json:"identifier"`
	Value      string    `json:"value"`
	ExpiresAt  time.Time `json:"expiresAt"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}
